id: P005644
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5002
  title: ཨོ་རྒྱན་བསྟན་འཛིན་གྱིས་བརྩམས་པའི་སྙན་ངག་ལེའུ་གཉིས་པའི་དཔེར་བརྗོད་བློ་གསར་དགའ་བའི་གླུ་དབྱངས་
  author: ''
  volumes: {}
