id: P005644
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG5002
  title: ཨོ་རྒྱན་བསྟན་འཛིན་གྱིས་བརྩམས་པའི་སྙན་ངག་ལེའུ་གཉིས་པའི་དཔེར་བརྗོད་བློ་གསར་དགའ་བའི་གླུ་དབྱངས་
  author: ''
  volumes:
    d4fad8b732b642e4b92e847accd3c78f:
      image_group_id: I1KG5076
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
